### ISSUE TITLE
Header x-correlator not included in the '200' response section

### ISSUE THREAD

**Issue by GillesInnov35** [camaraproject/Tenure#20]
**Problem description**
In the yaml file available in enure project, it seems that the header x-correlator which is mandatory is not included in the response '200' schema.
Do you confirm  ?

**Expected behavior**
Add header description as it is for the others errors sections

      responses:
        "200":
          description: Respond with tenure information
          headers:
            x-correlator:
              $ref: "#/components/headers/X-Correlator"

          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenureInfo"
    schemas:
      TenureInfo:
        properties:
          tenureDateCheck:
            description: |
              `true` when the identified mobile subscription has had valid tenure since `tenureDate`, otherwise `false`
            example: true
            type: boolean
          contractType:
            description: |
              If exists, populated with:
              - `PAYG` – prepaid (pay-as-you-go) account
              - `PAYM` – contract account
              - `Business` – Business (enterprise) account
              This attribute may be omitted from the response set where value is not known on the local MNO system.
            example: "PAYM"
            type: string
            enum: ["PAYG", "PAYM", "Business"]
        required:
          - tenureDateCheck

**Alternative solution**

**Additional context**

**Comment by eric-murray** [comment]
@GillesInnov35 
Yes, it is missing. Can you create the PR to fix this?

**Comment by fernandopradocabrillo** [comment]
Hi @GillesInnov35 
Thanks for the catch, yes it should be included.

```
responses:
    "200":
      description: Respond with tenure information
      headers: <-- this one
        x-correlator: 
          $ref: "#/components/headers/X-Correlator"

      content:
        application/json:
          schema:
            $ref: "#/components/schemas/TenureInfo"
```

We should also update the pattern to reflect the last agreement in commonalities:

```
headers:
    x-correlator:
      description: Correlation id for the different services
      schema:
        type: string
        pattern: ^[a-zA-Z0-9-]{1,55}$
  parameters:
    x-correlator:
      name: x-correlator
      in: header
      description: Correlation id for the different services
      schema:
        type: string
        pattern: ^[a-zA-Z0-9-]{1,55}$
        example: "b4333c46-49c0-4f62-80d7-f0ef930f1c46"
```
